---
- hosts: all
  tasks:
   - name: Install Chocolatey
     raw: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

   - name: Install SQL Server
     win_chocolatey:
      name: sql-server-express
      state: present

   - name: Reboot to apply changes
     win_reboot:
      reboot_timeout: 3600
